# This is an example template file that will be used to generate config files for the hyperparameter grid search.
# Every combination of parameters in the hyperparameters section will be created as a new config.
model: hourglass
hyperparameters:
  n_lm:
    - 49
    - 68
  n_hgs:
    - 3
    - 4
  n_res_modules:
    - 3
  n_features:
    - 512
  hg_depth:
    - 2
    - 4
  regression:
    - "dsnt"
  do_1x1_before_dsnt:
    - False
  heatmap_sigma:
    - 1.0
  augment_rotation:
    - 0
    - 15
    - 30
    - 60
    - 90
  loss_function:
    - "wing_10"
  normalize_loss:
    - False
  intermediate_loss:
    - False
  predict_distance_weight:
    - -1
  n_epoch:
    - 200
  batch_size:
    - 32
  lr_scheduler_patience:
    - 15
  lr_decay_factor:
    - 0.5
  lr: # learning rate
    - 0.001
  random_seed:
    - 0